#!/bin/sh
# Renders the Homebrew formula (macOS + Linux) for a released version
# and pushes it to the tedilabs/homebrew-tap repository.
#
# Runs in the release workflow after goreleaser has produced
# dist/checksums.txt. goreleaser's own Homebrew support does not fit:
# the brews section is deprecated (removed in v2.16) and
# homebrew_casks is macOS-only.
#
# Usage: publish-formula.sh vX.Y.Z
#   HOMEBREW_TAP_TOKEN  token with Contents read/write on the tap repo
#   DRY_RUN=1           print the formula instead of pushing
set -eu

VERSION="${1:?usage: publish-formula.sh vX.Y.Z}"
VER="${VERSION#v}"
TAP_REPO="tedilabs/homebrew-tap"
BASE="https://github.com/tedilabs/tfvault/releases/download/${VERSION}"

sha() {
  grep "  tfvault_${VER}_${1}.tar.gz\$" dist/checksums.txt | awk '{print $1}'
}

DARWIN_AMD64=$(sha darwin_amd64)
DARWIN_ARM64=$(sha darwin_arm64)
LINUX_AMD64=$(sha linux_amd64)
LINUX_ARM64=$(sha linux_arm64)
for v in "$DARWIN_AMD64" "$DARWIN_ARM64" "$LINUX_AMD64" "$LINUX_ARM64"; do
  [ -n "$v" ] || { echo "missing checksum in dist/checksums.txt" >&2; exit 1; }
done

# Note: the formula body is emitted by a function with a plain heredoc
# on purpose — embedding it in $(...) trips bash's command-substitution
# parser on the inner Ruby "<<~EOS" heredoc token.
render_formula() {
  cat <<EOF
# This file is generated by the tfvault release workflow. DO NOT EDIT.
class Tfvault < Formula
  desc "Universal Terraform credentials helper with pluggable secret backends"
  homepage "https://github.com/tedilabs/tfvault"
  version "${VER}"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "${BASE}/tfvault_${VER}_darwin_amd64.tar.gz"
      sha256 "${DARWIN_AMD64}"
    end
    if Hardware::CPU.arm?
      url "${BASE}/tfvault_${VER}_darwin_arm64.tar.gz"
      sha256 "${DARWIN_ARM64}"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "${BASE}/tfvault_${VER}_linux_amd64.tar.gz"
      sha256 "${LINUX_AMD64}"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "${BASE}/tfvault_${VER}_linux_arm64.tar.gz"
      sha256 "${LINUX_ARM64}"
    end
  end

  def install
    bin.install "tfvault"
  end

  def caveats
    <<~EOS
      Link the helper into Terraform's plugin directory:
        tfvault install

      Then add to your ~/.terraformrc:
        credentials_helper "tfvault" {
          args = []
        }

      Verify the setup with:
        tfvault status
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tfvault version")
  end
end
EOF
}

if [ "${DRY_RUN:-}" = "1" ]; then
  render_formula
  exit 0
fi

: "${HOMEBREW_TAP_TOKEN:?HOMEBREW_TAP_TOKEN is required}"

tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

git clone --depth 1 "https://x-access-token:${HOMEBREW_TAP_TOKEN}@github.com/${TAP_REPO}.git" "$tmp/tap"
mkdir -p "$tmp/tap/Formula"
render_formula > "$tmp/tap/Formula/tfvault.rb"

cd "$tmp/tap"
git config user.name "github-actions[bot]"
git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
git add Formula/tfvault.rb
if git diff --cached --quiet; then
  echo "formula unchanged, nothing to publish"
  exit 0
fi
git commit -m "feat: update tfvault to ${VERSION}"
git push origin HEAD
echo "published Formula/tfvault.rb ${VERSION} to ${TAP_REPO}"
